
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 941021
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
     ddl-auto:  update
    show-sql: true
mybatis:
  typeAliasesPackage: com.crk.gril.domain
  mapperLocations: classpath:mapper/*.xml
server:
  port: 8888
elasticsearch:
  firstIp: 127.0.0.1
  secondIp: 127.0.0.1
  thirdIp: 127.0.0.1
  firstPort: 9301
  secondPort: 9302
  thirdPort: 9303
  clusterName: cluster